dist: trusty

language: rust

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      script:
        - cargo build
    - rust: beta
      script:
        - cargo build
    - rust: nightly
      before_script:
        - rustup component add clippy-preview
      script:
        - cargo build
        - cargo clippy -- -D warnings
        - cargo test --features stainless